#! /usr/bin/env python3

import os
import sys
import urllib.parse as up
import pathlib

try:
    from tqdm import tqdm
    import requests
    from bs4 import BeautifulSoup
except ModuleNotFoundError:
    ret = os.system("pip install bs4 tqdm requests")
    if ret != 0:
        print("Running pip failed somehow. Please install 'tqdm', 'bs4' and 'requests' manually"
    print("Dependencies installed. please run again.")
    exit()

URL = "http://ftp.timepassbd.live"

def ls(path):
    f = up.unquote_plus(path.split('/')[-2])
    print("creating: " + f)
    try:
        os.mkdir(f)
    except FileExistsError:
        print("Folder ready. Proceeding.")
    except PermissionError:
        print("You do not have enough permission to download files here. Bye.")
        exit(1)
    os.chdir(f)
    data = requests.get(URL+path).text
    soup = BeautifulSoup(data,'html.parser')
    table = soup.table

    for tr in table:
        item_type = ''
        item_url = ''
        for td in tr:
            if td.name == 'td':
                if td.img != None:
                    item_type = td.img['alt']
                if td.a != None:
                    item_url = td.a['href']
        if item_type == 'folder':
            ls(item_url)
            os.chdir("..")
        elif item_type == 'file':
            file_name = up.unquote_plus(item_url.split("/")[-1])
            res = requests.get(URL+item_url,stream=True)
            total_size = int(res.headers.get('content-length',0))
            block_size = 1024
            file = pathlib.Path(file_name)
            print("Downloading: " + file_name)
            if file.exists():
                if file.stat().st_size == total_size:
                    print("File already downloaded.")
            else:
                with tqdm(total=total_size, unit="B",unit_scale=True,colour='GREEN') as pbar:
                    with open(file_name, "wb") as file:
                        for data in res.iter_content(block_size):
                            pbar.update(len(data))
                            file.write(data)
                if total_size != 0 and pbar.n != total_size:
                    print("Download failed.")
        else:    
            pass

try:
    if len(sys.argv) < 2:
        print("Need timepassbd url")
        exit()

    if sys.argv[1].startswith("http://ftp.timepassbd.live"):
        ls(sys.argv[1][26:])
    elif sys.argv[1].startswith("/timepassbd-data")
        ls(sys.argv[1])
    else:
        print("invalid url")
except KeyboardInterrupt:
    print("Bye.")
