#! /usr/bin/env python3

import datetime
import os
import re
import sys
import time
import traceback
import urllib.parse as up
from concurrent.futures import ThreadPoolExecutor
from enum import Enum
from typing import Self, override

FMSearchRegex = re.compile("""href=["']([^.].+)["']""", re.IGNORECASE)

# Dependency Warning
try:
    import argparse

    import requests
    from tqdm import tqdm
except ModuleNotFoundError as _e:
    print("""
ftpdl requires:
    BeautifulSoup
    Tqdm
    Request

Install with the following command:
    pip3 install bs4 tqdm requests --break-system-packages
If inside a virtual env:
    pip install bs4 tqdm requests --break-system-packages
""")
    sys.exit(1)

# Server base URLs
TIMEPASSBD_URL = "http://ftp.timepassbd.live"
FMFTP_URL = "https://fmftp.net"

# Log Init
DATA_DIR = os.getenv("HOME") + "/.ftpdl"
if not os.path.exists(DATA_DIR):
    os.mkdir(DATA_DIR)
date = datetime.datetime.now().strftime("%Y-%m-%d.T%H-%M")
log = open(f"{DATA_DIR}/ftpdl.{date}.err.log", "w")


# A class to hold item data
class FTPType(Enum):
    FILE = 0
    FOLDER = 1

    @classmethod
    def getType(cls, url: str):
        if url.endswith("/"):
            return cls.FOLDER
        else:
            return cls.FILE


class FTPItem:
    name: str
    url: str
    type: FTPType

    def __init__(self: Self, url: str):
        self.url = url
        self.type = FTPType.getType(url)
        if self.type == FTPType.FILE:
            self.name = up.unquote_plus(url.split("/")[-1])
        else:
            self.name = up.unquote_plus(url.split("/")[-2])

    @override
    def __str__(self):
        return f"{self.name} is a {self.type}"


def not_implemented():
    print("Feature not yet implemented !")
    sys.exit(0)

def fmftp_logic(url: str) -> list[FTPItem]:
    itemList = []
    data = requests.get(url).text
    data = FMSearchRegex.findall(data)
    for item in data:
        itemList.append(FTPItem(url + item))

    return itemList

# a function that makes folder list
def makeList(i: FTPItem) -> list[FTPItem]:
    if i.url.startswith(FMFTP_URL):
        return fmftp_logic(i.url)
    else:
        not_implemented()

# Logic for timepassbd anfd ftpbd
def download(item: FTPItem):
    file_name = item.name
    res = requests.get(item.url, stream=True)
    total_size = int(res.headers.get("content-length", 0))
    resume = False
    if os.path.exists(file_name):
        file = open(file_name, "rb+")
        _ = file.seek(0, 2)
        file_size = file.tell()
        if file_size == total_size:
            print(f"{file_name}: File exists.")
            return

        res.close()
        res = requests.get(
            item.url, stream=True, headers={"Range": f"bytes={file_size}-{total_size}"}
        )
        resume = True
    else:
        file = open(file_name, "wb+")

    block_size = 8192
    if resume:
        print("Resuming: " + file_name)
        with tqdm(
            initial=file_size,
            total=total_size,
            unit="B",
            unit_scale=True,
            colour="BLUE",
        ) as pbar:
            for data in res.iter_content(block_size):
                pbar.update(len(data))
                file.write(data)
    else:
        print("Downloading: " + file_name)
        with tqdm(total=total_size, unit="B", unit_scale=True, colour="#800020", ascii=True) as pbar:
            for data in res.iter_content(block_size):
                pbar.update(len(data))
                file.write(data)

    file.close()
    if total_size != 0 and pbar.n != total_size:
        print("Download failed.")


def do_search(item: FTPItem, sk: str) -> bool:
    if item.name.lower().__contains__(sk.lower()):
        print(f"Found: {item.name}\nAt: {item.url}", flush=True)
        return True
    return False


# experimental thread support
thread = int(os.environ.get("FTPDL_THREAD", "1"))
if thread != 1:
    tpe = ThreadPoolExecutor(max_workers=thread)


# process everything inside
def process(url: str, search: bool, keyw: str = ""):
    i = FTPItem(url)
    if search:
        if i.type == FTPType.FOLDER:
            if do_search(i, keyw):
                return
            else:
                for item in makeList(i):
                    if thread != 1:
                        _ = tpe.submit(process, item.url, search, keyw)
                    else:
                        process(item.url, search, keyw)
        else:
            if do_search(i, keyw):
                return

    else:
        if i.type == FTPType.FILE:
            download(i)
        else:
            if not os.path.exists(i.name):
                print(f"Creating {i.name}")
                os.mkdir(i.name)

            print(f"Entering {i.name}")
            os.chdir(i.name)

            for item in makeList(i):
                if thread != 1:
                    _ = tpe.submit(process, item.url, search, keyw)
                else:
                    process(item.url, search, keyw)
            print("Going back")
            os.chdir("..")


def main(url: str, search: bool, keyw: str):
    global thread
    try:
        if not search:
            thread = 1
        process(url, search, keyw)
    except KeyboardInterrupt:
        print("User terminated.")
        if thread != 1:
            tpe.shutdown(wait=False)
        sys.exit(0)
    except Exception as e:
        print("Some error occured. See the log file.")
        _ = log.write(f"{e}\n\n")
        _ = log.write(f"{traceback.format_exc()}")
        log.close()
        sys.exit(1)


# game begins
parser = argparse.ArgumentParser()
_ = parser.add_argument("-d", "--download", help="Downloads a given url.")
_ = parser.add_argument("-s", "--search", help="search for given keyword")

arg = parser.parse_args()

if arg.search:
    if arg.download:
        print(f"searching in: {FTPItem(arg.download).name}")
        main(arg.download, True, arg.search)
    else:
        print("Searching....")
        main(f"{FMFTP_URL}/data/", True, arg.search)
    if thread != 1:
        while not tpe._work_queue.empty():
            time.sleep(10)
    sys.exit()

if arg.download:
    main(arg.download, False, "")
    sys.exit()

if os.path.exists("ftpdl.link"):
    with open("ftpdl.link", "rt") as link_file:
        for line in link_file:
            main(line.strip(), False, "")
        sys.exit()
else:
    print("Please create a ftpdl.link file or provide a URL.")
    sys.exit(1)
