#! /usr/bin/env python3

import os
import threading

try:
    import requests
    from bs4 import BeautifulSoup
except ModuleNotFoundError:
    ret = os.system("pip install bs4 requests")
    if ret != 0:
        print("Running pip failed somehow. Please install 'bs4' and 'requests' manually")
    print("Dependencies installed. please run again.")
    exit()

TIMEPASSBD_URL = "http://ftp.timepassbd.live"
FTPBD2_URL = "http://server2.ftpbd.net"
FTPBD3_URL = "http://server3.ftpbd.net"
FTPBD4_URL = "http://server4.ftpbd.net"
FTPBD5_URL = "http://server5.ftpbd.net"
DATA_DIR = os.getenv("HOME") + "/.ftpdl"

count = 0
file = open(DATA_DIR+"/all.ftp.index","w")
err_file = open(DATA_DIR+"/all.error","w")
empty = open(DATA_DIR+"/all.empty","w")

try:
    os.mkdir(DATA_DIR)
except FileExistsError:
    pass
except OSError:
    print("Could not create folder Bye.")
    exit()

def ls(base_url,path):
    global count
    global file
    try:
        data = requests.get(base_url+path).text
        soup = BeautifulSoup(data,'html.parser')
    except:
        return
    table = soup.table

    if table == None:
        empty.write(base_url + path + ": seems to have nothing\n")
        return

    for tr in table:
        item_type = ''
        item_url = ''
        for td in tr:
            if isinstance(td,str):
                err_file.write(base_url+path + " has prob\n")
                continue
            if td.name == 'td':
                if td.img != None:
                    item_type = td.img['alt']
                if td.a != None:
                    item_url = td.a['href']
        if item_type == 'folder':
            ls(base_url,item_url)
        elif item_type == 'file':
              count = count + 1
              print("indexed: " + str(count) + " item.",end="\r")
              try:
                file.write(base_url+item_url+"\n")
              except:
                print("File write failed.")
        else:    
            pass

def timepassbd():
    global file
    global count
    print("From ftp.timepassbd.live: ")
    ls(TIMEPASSBD_URL,"/")

def ftpbd2():
    global file
    global count
    print("From server2.ftpbd.net/FTP-2: ")
    ls(FTPBD2_URL,"/FTP-2")

def ftpbd3():
    global file
    global count
    print("From server3.ftpbd.net/FTP-3: ")
    ls(FTPBD3_URL,"/FTP-3")

def ftpbd4():
    global file
    global count
    print("From server4.ftpbd.net/FTP-4: ")
    ls(FTPBD4_URL,"/FTP-4/Tutorial")

def ftpbd5():
    global file
    global count
    print("From server5.ftpbd.net/FTP-5: ")
    ls(FTPBD5_URL,"/FTP-5")

a = threading.Thread(target=timepassbd)
b = threading.Thread(target=ftpbd2)
c = threading.Thread(target=ftpbd3)
d = threading.Thread(target=ftpbd4)
e = threading.Thread(target=ftpbd5)
# timepassbd()
# ftpbd2()
# ftpbd3()
# ftpbd4()
# ftpbd5()
a.start()
b.start()
c.start()
d.start()
e.start()
a.join()
b.join()
c.join()
d.join()
e.join()