#! /bin/bash

INTERFACES=$(ifconfig -l -u)

for i in $INTERFACES
do
    IFCFG=$(ifconfig "$i")
    IP4=$(echo "$IFCFG" | grep -E -o "inet [0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}\.[0-9]{0,3}" | sed -e "s/inet//g")
    IP6=$(echo "$IFCFG" | grep -E -o "inet6 [[:alnum:]]{0,4}:[[:alnum:]]{0,4}:[[:alnum:]]{0,4}:[[:alnum:]]{0,4}:[[:alnum:]]{0,4}:[[:alnum:]]{0,4}" | sed -e "s/inet6//g")


    if [[ $IP4 != "" || $IP6 != "" ]]
    then
        echo -e "Interface \033[34m$i:"
    fi
    if [[ $IP4 != "" ]]
    then
        echo -e "\t\033[32m$IP4\033[0m"
    fi
    if [[ $IP6 != "" ]]
    then
        echo -e "\t\033[31m$IP6\033[0m"
    fi
done
