#! /bin/bash

command_c="clang"
command_cpp="clang++"
command_java="javac"

if [[ $1 = "" ]]
then
  echo "No file was given"
  exit
fi

format=`echo $1 | cut -d "." -f 2 -s`

if [[ $format = "" ]]
then
  echo "Invalid file"
  exit
fi

output=`echo $1 | cut -s -d "." -f 1`

if [[ $format = "c" ]]
then
  command="$command_c -o $output"
elif [[ $format = "cpp" ]]
then
  command="$command_cpp -o $output"
elif [[ $format = "java" ]]
then
  command="$command_java"
fi

$command $1

if [[ $? -eq 0 ]]
then
  echo -e "\033[33mRunning: $output\033[0m"
  if [[ $format != "java" && $TERMUX_VERSION ]]
  then
    termux-elf-cleaner $output 2&>1 /dev/null
  fi
  if [[ $format = "java" ]]
  then
    java $output
  else
    ./$output
  fi
fi
